version: "3.9"

services:
  backend:
    build:
      context: ./Backend/Backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "5000:5000"   # host 5000 maps to container 5000
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "80:80"       # host 80 maps to container 80
    restart: unless-stopped
    depends_on:
      - backend
